### ISSUE TITLE
SOAPFAULT e JWT

### ISSUE THREAD

**Issue by charlesreitz** [totvs/tlpp-sample-rest#1]
Olá, tem como tratar um soapfault no rest do tlpp? 

Existe alguma forma de tratar JWT?

**Comment by denardi-totvs** [comment]
Olá Charles,
Boa tarde!

Seguem esclarescimentos:

**"tem como tratar um soapfault no rest do tlpp?"**

É possível através do método setFault(), veja doc em:
https://tdn.totvs.com/display/tec/oRest%3AsetFault

ficando a sintaxe:
`oRest:setFault( "mensagem de erro" )`

Para saber mais detalhes do objeto oRest, acesse:
https://tdn.totvs.com/display/tec/4+-+Entendendo+o+objeto+oREST

**Comment by denardi-totvs** [comment]
**"Existe alguma forma de tratar JWT?"**

Para JWT a funcionalidade está em implementação, já existe a ISSUE interna da equipe do tlppCore de número [DTTLPP-1852].

Porém, existe duas possibilidades de autenticação no REST tlpp atual, seguem:

BASIC:
https://tdn.totvs.com/display/tec/oAuth

oAuth2:
https://tdn.totvs.com/display/tec/oAuth2
