### ISSUE TITLE
Includes

### ISSUE THREAD

**Issue by danielAlbuquerque** [totvs/tlpp-sample-rest#2]
Onde estão as includes do TLPP? Nao tem disponivel pra download no portal

**Comment by denardi-totvs** [comment]
Olá Daniel!

Por favor, siga os passos contidos nessa documentação:
https://tdn.engpro.totvs.com.br/pages/viewpage.action?pageId=555860439

Att,
Denardi

**Comment by danielAlbuquerque** [comment]
Obrigado, ne epoca ainda nao tinha essa documentacao. 
Ja estou utilizando essas e esperando ansioso pelas de testes unitarios.

**Comment by denardi-totvs** [comment]
Olá Daniel,

Agora você consegue obter o include do "Test Engine", além do patch do módulo para uso.

Veja em:
https://tdn.totvs.com/display/tec/Downloads

Existem duas documentações:
https://tdn.totvs.com/display/tec/Engine+de+Testes
https://tdn.totvs.com/pages/viewpage.action?pageId=452400318

1 - Estamos trabalhando para ter somente uma DOC oficial, além de atualizá-la, pois existem novos recursos.

2 - Iremos disponibilizar um projeto no GitHub com exemplos de como utilizar os recursos.
Porém, enquanto não sair esse projeto e tiver dificuldades, me procure.

Abs,
Denardi

**Comment by denardi-totvs** [comment]
Olá @danielAlbuquerque !
Tudo bem?

Agora temos somente uma única documentação sobre o Motor de Testes PROBAT, segue:
https://tdn.totvs.com/display/tec/PROBAT

Você pode também acessar os exemplos em:
https://github.com/totvs/tlpp-probat-samples

Abs,
Denardi
