### ISSUE TITLE
Como faço para subir as empresas do Protheus no TLPP Rest? 

### ISSUE THREAD

**Issue by charlesreitz** [totvs/tlpp-sample-rest#3]
Como faço para subir as empresas do Protheus no TLPP Rest? 

No antigo tínhamos -> PrepareIn=T1,D MG 01

https://tdn.totvs.com/display/framework/02.+REST+com+ERP+Microsiga+Protheus

**Comment by denardi-totvs** [comment]
Olá Charles,

Quando utilizamos o REST nativo do tlppCore, você possui o controle em alguns pontos, veja a DOC:
https://tdn.totvs.com/pages/viewpage.action?pageId=553330377

Para a abertura de empresa e filial, utilize o OnStart, sendo assim, na criação da Thread utilizada pelo REST tlpp será invocada a função que você informar.
Portanto, nessa função você tem a possibilidade por você mesmo abrir a empresa e filial conforme lhe convém.

Vamos exemplificar:

No ini, ao configurar, utilize a chave "UserExits" na configuração de sua ThreadPool, como segue:

```
[HTTPSERVER]
Enable=1
Servers=HTTP_NO_SSL

[HTTP_NO_SSL]
hostname=localhost
port=9080
locations=HTTP_ROOT

[HTTP_ROOT]
Path=/
RootPath=root/web
DefaultPage=index.html
AllowMethods=DELETE, GET, OPTIONS, PATCH, POST, PUT
ThreadPool=THREAD_POOL

[THREAD_POOL]
Environment=TLPPCORE
UserExits=THREAD_POOL_01_UEX
...

[THREAD_POOL_01_UEX]
OnStart=U_MyStart
```

Após isso, implemente a sua função e compile em seu ambiente:

```
user function MyStart()
	
	local lEnv := abreEmpresaFilial() // Funcao ficticia para vc implementar a sua logica de abertura e empresa filial
	
	if ( valtype(lEnv) <> 'L' )
		lEnv := .F.
	endif
return lEnv
```

Importante ressaltar, que é obrigatório o retorno do tipo boolean, indicando .T. para que o REST suba essa thread, e .F. para que a thread nem seja inicializada.

Outro ponto importante a se ressaltar, é que quando você opta pelo controle de empresa e filial em sua camada, é aconselhável você também controlar a distribuição das threads através do "OnSelect", assim dessa forma você garante que a requisição será processada pela thread onde foi aberto a empresa e filial correta, evitando problemas de ambiente.

Veja mais detalhes sobre OnSelect em:
https://tdn.totvs.com/display/tec/onSelect
